#include "tasks/apserver.hpp"
#include <pinicore.hpp>
#include "global.hpp"
#include "utils.hpp"

#define TAG_TASK_APSERVER  "task_apserver"

// Symbols generated by PlatformIO's board_build.embed_txtfiles.
// - Web Pages (*.html)
extern const uint8_t web_index_html_start[]   asm("_binary_src_web_index_html_start");
extern const uint8_t web_index_html_end[]     asm("_binary_src_web_index_html_end");
extern const uint8_t web_404_html_start[]     asm("_binary_src_web_404_html_start");
extern const uint8_t web_404_html_end[]       asm("_binary_src_web_404_html_end");

// Symbols generated by PlatformIO's board_build.embed_txtfiles.
// - Resources (*.css)
extern const uint8_t web_resources_style_css_start[]  asm("_binary_src_web_resources_style_css_start");
extern const uint8_t web_resources_style_css_end[]    asm("_binary_src_web_resources_style_css_end");
extern const uint8_t web_resources_404_css_start[]    asm("_binary_src_web_resources_404_css_start");
extern const uint8_t web_resources_404_css_end[]      asm("_binary_src_web_resources_404_css_end");


void TaskAPServer::init() {
    if (m_initialized) return;
    m_wifi.init();
    m_wifi.enable();
    m_wifi.configAP(AP_SSID, AP_PASSWORD, false);
    m_wifi.connectAP();
    m_webServer.onNotFound([this]() { onRequestNotFound(); });
    m_webServer.on("/", HTTP_GET, [this]() { onRequestIndex(); });
    m_webServer.on("/resources/style.css", HTTP_GET, [this]() { onRequestStyle(); });
    m_webServer.on("/resources/404.css", HTTP_GET, [this]() { onRequestNotFoundStyle(); });
    m_webServer.begin();
    m_initialized = true;
}

void TaskAPServer::onRequestNotFoundStyle() {
    m_webServer.send_P(
        200,
        "text/css",
        reinterpret_cast<const char*>(web_resources_404_css_start),
        web_resources_404_css_end - web_resources_404_css_start
    );
}

void TaskAPServer::onRequestNotFound() {
    m_webServer.send_P(
        404,
        "text/html",
        reinterpret_cast<const char*>(web_404_html_start),
        web_404_html_end - web_404_html_start
    );
}

void TaskAPServer::onRequestStyle() {
    m_webServer.send_P(
        200,
        "text/css",
        reinterpret_cast<const char*>(web_resources_style_css_start),
        web_resources_style_css_end - web_resources_style_css_start
    );
}

void TaskAPServer::onRequestIndex() {
    m_webServer.send_P(
        200,
        "text/html",
        reinterpret_cast<const char*>(web_index_html_start),
        web_index_html_end - web_index_html_start
    );
}

void TaskAPServer::loop() {
    m_webServer.handleClient();
    taskYIELD();
}

void TaskAPServer::deinit() {
    if (!m_initialized) return;
    m_webServer.stop();
    m_wifi.disable();
    m_initialized = false;
}
