; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_echo = yes
monitor_speed = 115200
monitor_filters = time, log2file
build_src_filter = +<*> -<.git/> -<.svn/> -<main*.cpp> +<main.cpp>
build_flags = 
	-std=c++17
	-std=gnu++17
    -Desp_cpu_get_cycle_count=esp_cpu_get_ccount
lib_deps =
    https://github.com/PiniponSelvagem/PiniCore-Embedded
    ;https://github.com/PiniponSelvagem/PiniCore-Embedded@1.0.1
    https://github.com/Mystfit/ESP32-BLE-CompositeHID@0.4.0
    chrissb/PCAL9535A Library@^1.2.4

[env:GAMEPAD]
lib_deps = 
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}

[env:DEBUG_GAMEPAD]
extends = env:GAMEPAD
build_flags = 
    ${env:GATEWAY.build_flags}
    -D PLOG_LEVEL=PLOG_LEVEL_VERBOSE