require('./styles/base.css')
require('./styles/theme.css')
require('./styles/layout.css')
require('./styles/navigation.css')
require('./styles/pages/controller.css')
require('./styles/pages/settings.css')
require('./styles/responsive.css')
require('./js/main')